### ISSUE TITLE
Add option to hide page-link href

### ISSUE THREAD

**Issue by samgavinio** [flaviusmatis/simplePagination.js#101]
There may be cases where adding inpage reference in the page hyperlinks is not desired. You could empty both `hrefTextPrefix` and `hrefTextSuffix` but you can't get rid of the page number. Some people prefer `javascript:void(0);` instead.

**Comment by flaviusmatis** [comment]
You can simply use the onPageClick handler to prevent clicks on pagination items.

**Comment by bilalakil** [comment]
If the `onPageClick` handler returns false then the page fragment won't be changed.
