### ISSUE TITLE
simplePagination doesn't work for bigger tables

### ISSUE THREAD

**Issue by negar7aref** [flaviusmatis/simplePagination.js#107]
Hi Flavius,

Thank you very much for creating simplePagination. I am using it and it works perfectly with small tables. However, my tables are sometimes huge (at least 1,000,000 rows). In these cases simplePagination doesn't work since it waits for the page to load first. The loading takes a long time and quickly eats up the memory so browsers crash before simplePagination can ever take effect. Is there anyway to customize simplePagination for huge tables? If not, could you please advise me how to fix this issue without using a database?

**Comment by timgws** [comment]
@negar7aref this is not really what simplePagination is for. Maybe you should look at Datatables with AJAX requests if you want to load data into a table with a database backend.
