### ISSUE TITLE
Add First & Last and SKIP 

### ISSUE THREAD

**Issue by ViaJasmine** [flaviusmatis/simplePagination.js#114]
I would like for you to add a "first" and "last page" to this javascript.

Also I would like to know how to add a "skip"
e.g. ">>>" & "<<<" that would skip the pages by 5 or 10 pages.

Thanks

**Comment by ragefuljoe** [comment]
first and last  you could do yourself, just bind something to call $pagination.pagination("selectPage", 1); and $pagination.pagination("selectPage", $pagination.pagination("getPagesCount"));

**Comment by Method-Development** [comment]
Hmm, I cannot seem to get that to work.

**Comment by venukumarvk** [comment]
> Hmm, I cannot seem to get that to work.
> 
> Nevermind, I got it to work.

Hi 
    Can you please help me to solve this issue, i'm stuck on this issue right now.
