### ISSUE TITLE
Next jumping to last

### ISSUE THREAD

**Issue by ronGP1** [flaviusmatis/simplePagination.js#117]
Hello and thanks for this great paginator.

Let's say I have 72 pages I'm paging using the next button, when I reach page 15 it will jump to the last page instead of going to page 16.

If i put an alert just before the function it works right.

Any clues? Thanks.

	items: 359,
        itemsOnPage: 5,
        cssStyle: 'compact-theme',
        prevText: '<',
        nextText: '>',
        currentPage: currentPnum,
        displayedPages: 24,
        edges: 3,

**Comment by stuplove** [comment]
are you check currentPnum ?

**Comment by ronGP1** [comment]
Problem is solved it was my mistake.
