### ISSUE TITLE
How to point to the pages

### ISSUE THREAD

**Issue by petejunior** [flaviusmatis/simplePagination.js#123]
I have installed "successfully" this script on my 'index'.html page.
How to add 2 other pages , so that to make the script really working ?
The names of the other pages are 'index2.html' and 'index3.html'...
Where  i have to define them and ....how ?
10x in advance

**Comment by mcfee1979** [comment]
I'd like to know this too if anyone can help please?

**Comment by petejunior** [comment]
jkl;jkl
