### ISSUE TITLE
print paginated table

### ISSUE THREAD

**Issue by gdguradio** [flaviusmatis/simplePagination.js#126]
I have a table which is paginated using simple pagination. The entry per page is only 10. I want to print all the pages but I have no idea how to. I can print them one by one using 

```
$('.printMe').click(function(){
     window.print();
});
```

 I added 

```
.dontprint{ 
    display : none
}
```

for elements that i don't need to print that includes the button in the pagination. The div that contains the number of pages 

**If i have 50 pages that is so much click and waste of time.**

`Note:`

I. Even if i add _dontprint class_ to the pagination pages _it wont disappear during printing_

**Comment by JosephMart** [comment]
Is there no solution for this?
