### ISSUE TITLE
How to use simplePagination on html automatically generated by another plugin?

### ISSUE THREAD

**Issue by hummelss** [flaviusmatis/simplePagination.js#131]
I am sorry for my stupid question. I've sucessfully installed the plugin, but I dont know how to set it.

Example:

```
    <div class="testimonial-group">

        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>
        <div class="testimonial"></div>

    </div>

    <div class="reviewspagination"></div> 
```

I have 10 children elements and I want to show 5 elements on each page. So how can I set the plugin to work for this html. Thank you in advance

**Comment by AlexEndris** [comment]
You would have to hide all elements you don't want to show and have the logic that shows the elements in the 'onPageClick' callback.
