### ISSUE TITLE
How to prevent URL updating?

### ISSUE THREAD

**Issue by bbappyuanyuan** [flaviusmatis/simplePagination.js#139]
onPageClick() will always update the URL. How to prevent it?

**Comment by jross-imsteris** [comment]
latest pull into master gives an option to turn it off.

**Comment by dhruv-m-patel** [comment]
Tried this out. When setting `onPageClick`, it needs a little modification like this:

```
onPageClick(page, e) {
    // your code to handle page change
    e.preventDefault();
},
```
