### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by euston007** [flaviusmatis/simplePagination.js#14]
I really like your plugin but when I try and use it I get the paging but no table records? Which selector do I need to use from the code below: It looks like the pagination js injects the paging links into the selector but how does it redisplay the table rows?

Here is my html structure:

<div id="tablerecords">
    <table id="pagelist" class="oServices row-highlight paginated" summary="List of Draft Library Pif Records">
            <thead>
            <tr>
                            <th class="sort-date">Date Created</th>
                            <th class="sort-alpha">Library Name</th>
                            <th class="sort-month">Month</th>
                            <th>Financial Year</th>
                            <th>Authority</th>
                            <th>Visitors</th>
                            <th>Details</th>
                            <th>Edit</th>
                </tr>
            </thead>
        <tbody>
               <tr>
                   <td></td><td></td>etc
                </tr>
                
                  </tbody>
    </table>
   
   </div>

My JS code is:

```
$(function () {
    $('#pagelist').pagination({
        items: 24,
        itemsOnPage: 8,
        cssStyle: 'light-theme'
    });
});
```

**Comment by mhulse** [comment]
@bilalakil thanks for the blog post and code example!

Just for posterity's sake, here's the code sample from @bilalakil's blog post:

```js
jQuery(function($) {
    // Grab whatever we need to paginate
    var pageParts = $(".paginate");

    // How many parts do we have?
    var numPages = pageParts.length;
    // How many parts do we want per page?
    var perPage = 2;

    // When the document loads we're on page 1
    // So to start with... hide everything else
    pageParts.slice(perPage).hide();
    // Apply simplePagination to our placeholder
    $("#page-nav").pagination({
        items: numPages,
        itemsOnPage: perPage,
        cssTheme: "light-theme",
        // We implement the actual pagination
        //   in this next function. It runs on
        //   the event that a user changes page
        onPageClick: function(pageNum) {
            // Which page parts do we show?
            var start = perPage * (pageNum - 1);
            var end = start + perPage;

            // First hide all page parts
            // Then show those just for our page
            pageParts.hide()
                     .slice(start, end).show();
        }
    });
});
```

Note that when I was working with a list, and had the `ul` selected/cached, I had to do this:

```js
$ul.children('li').slice(5)
```

… and `cssStyle` should replace `cssTheme` in above code sample.

**Comment by bilalakil** [comment]
@mhulse, thanks for pointing out the `cssTheme` problem. I've no idea how long I've been doing it wrong >< I'll fix it... everywhere.

**Comment by mhulse** [comment]
Oh, no worries @bilalakil! I just figured maybe there used to be a `cssTheme` option? No biggy though. THanks so much for sharing the code, it really helped me get my app working just right. :+1: :octocat:
