### ISSUE TITLE
Two divs with two paginations

### ISSUE THREAD

**Issue by JuanDBB** [flaviusmatis/simplePagination.js#66]
Hello,
Great plugin ))
I have two divs showed alternatively through tabs in the same page, each with each own pagination, but the second pagination doesn't appear. Does the plugin supports that?

Thank you in advance.

Sorry, was my code. Everything works great ))

**Comment by ykliao** [comment]
I had the same requirement and solved in the following way. In short, just add the same class to the two divs then use the name as the selector before creating the pager. 

As an example, assuming jQuery is being used. 

On the page, 
<div id="pagination1" class="pagination"></div>
<div id="pagination2" class="pagination"></div>

Run the jQuery code
