### ISSUE TITLE
Pagination not a function

### ISSUE THREAD

**Issue by Argon-MGLM** [flaviusmatis/simplePagination.js#84]
I tried using the js file for including the pagination in my webpage but it is showing in browser console
TypeError: $(...).pagination is not a function
what can be the possible problem/issue with it,
note:
I am using require.js to get the scripts loaded
Please replay, thanks in advance

**Comment by resoliwan** [comment]
if you use jquery plug-in not support requirejs use shim config 
check http://requirejs.org/docs/api.html#config-shim

example 
common.js
'shim': {
    'vendor/jquery.simplePagination': {deps:['jquery']}
  }

use at

define(['jquery', 'vendor/jquery.simplePagination']
  , function ($, simplePagination) {

  });

i use simplePagination.js with requirejs but it work well :)

**Comment by Argon-MGLM** [comment]
issue is solved thanks for the answer...
