### ISSUE TITLE
displayedPages logic - not as expected

### ISSUE THREAD

**Issue by dankarmy** [flaviusmatis/simplePagination.js#92]
Taken from the documentation:

displayedPages

How many page numbers should be visible while navigating.

So if I set this to 5 (the default) - I would expect to see (maximum):

Prev + Edges + Interval Pages + Edges + Next

Where as, the Interval pages seems to range anywhere from 3 to 6 (bringing the total links to 12! - 10 if you take off prev/next)

This cannot be right surely?

You can see this for yourself on the light theme demo http://flaviusmatis.github.io/simplePagination.js

Any ideas?

**Comment by timgws** [comment]
This is to be expected. `displayedPages` is the number of interval pages (so it will show `(displayedPages-1)/2` on the left and right side of the current page you are on.

![screen shot 2015-03-10 at 10 41 03 am](https://cloud.githubusercontent.com/assets/1050232/6567046/9bd4154e-c715-11e4-8b54-85a50a029176.png)

This is from `displayedPages` being set explicitly to 5, with `edges` being set to 1.
