### ISSUE TITLE
Remove last page number as a initializing option

### ISSUE THREAD

**Issue by shyamdadimuni** [flaviusmatis/simplePagination.js#97]
Hi,

This is a great plugin. I'm using it in our search page.

We are using GoogleMini and it is returning estimated result count, and always this is not true. So I would like to remove last page number and display only given number of pages, as we see in Google result page (see image). 

![image](https://cloud.githubusercontent.com/assets/5640095/6743549/b80f53b4-ce71-11e4-8f80-21b7571ef0d0.png)

One thing I would like to add, "First" link when Page number 1 is not show in pagination.

Thanks,
Shyam

**Comment by resoliwan** [comment]
useEndEdge:false

```
$('<div id="edge_pager" class="pager"></div>').appendTo('body').pagination({
		items: items,
		itemsOnPage: itemsOnPage,
		useStartEdge:false,
		useEndEdge:false
	})

	edgePager = $('#edge_pager');
})

it('pages should same text when select 1 page', function() {
	edgePager.pagination('selectPage', 1);
	expect(edgePager).toBeSameTextValues(['Prev', '1', '2', '3', '4', '5', '...', 'Next']);
})

it('pages should same text when select last page', function() {
	edgePager.pagination('selectPage', pageCount);
	expect(edgePager).toBeSameTextValues(['Prev', '...', '6', '7', '8', '9', '10', 'Next']);
})
```

**Comment by shyamdadimuni** [comment]
Thanks
