### ISSUE TITLE
ReferenceError: e is not defined with selectPage function

### ISSUE THREAD

**Issue by jarodd** [flaviusmatis/simplePagination.js#98]
Hi, 

I have an issue using the selectPage function. I have another functionality on my website, to sort items. After sorting them, I want to call the selectPage function to set the pagination at the first page, I do this with this code :
$("#pagination").pagination('selectPage', 1); 

I use the plugin as this : 
$("#pagination").pagination({
    items: numItems,
    itemsOnPage: perPage,
    cssStyle: "",
    prevText: 'Précédent',
    nextText: 'Suivant',
    onPageClick: function(pageNumber, e) { // this is where the magic happens
        e.stopPropagation(); // e.preventDefault();
        // my stuff
    }
}); 

The "onPageClick" property of the plugin  want a event parameter too (lines 34~37 of jquery.simplePagination.js) : 
onPageClick: function(pageNumber, event) {
    // Callback triggered when a page is clicked
    // Page number is given as an optional parameter
}

But I have this error : 
ReferenceError: e is not defined functions.js:79:4

Line 79 is « $("#pagination").pagination('selectPage', 1); » code. This is the same code in the documentation : 
$(selector).pagination('selectPage', pageNumber);
I don't see any event parameter here...

I don't understand what I have to write to avoid this error.

Hope you can help me :)

**Comment by GreeKatrina** [comment]
I ran into this issue as well, except it was for the updateItemsOnPage function.

My fix was to add the event parameter in the source code.

The current source code is this for selectPage:

```javascript
selectPage: function(page) {
    methods._selectPage.call(this, page - 1);
    return this;
},
```
In order for your example to work, you want to change it to this:

```javascript
selectPage: function(page, event) {
    methods._selectPage.call(this, page - 1, event);
    return this;
},
```
